[project]
name = "CheetahPy"
version = "0.2.1"
description = "Python API for accessing Golden Cheetah"
readme = "README.md"
authors = [
  { name="Ryan Duecker", email="ryan.duecker@yahoo.com" },
]
license = {file = 'LICENSE'}
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]